#define MSG_WEATHER_ENABLED 1
#define MSG_WIFI_RECONNECT 2
#define MSG_WEATHER_CITY_CHANGED 3
#define MSG_WEATHER_LANGUAGE_CHANGED 4
#define MSG_AUTO_BRIGHTNESS 5
#define MSG_WEATHER_UPDATE 6
#define MSG_WIFI_CONNECTED 7
#define MSG_WIFI_DISCONNECTED 8