//LCD PINS
#define LCD_MOSI 23
#define LCD_MISO 19
#define LCD_SCK 18
#define LCD_CS 5
#define LCD_RST 15
#define LCD_DC 2
#define LCD_BACKLIGHT 32 

//TOUCHSCREEN PINS
#define TS_MOSI LCD_MOSI
#define TS_MISO LCD_MISO
#define TS_SCK LCD_SCK
#define TS_CS 4

//SD CARD SHOULD USE DEDICATED SPI BUS
//SD READER PINS
#define SD_MOSI 13
#define SD_MISO 33
#define SD_SCK 14
#define SD_CS 27

//RGB PIN
#define RGB_PIN 26

//TOUCH SENSOR BUTTON PIN
#define BUTTON_PIN 35

//TOUCH SENSOR BUTTON PIN
#define BATTERY_LEVEL_PIN 34
#define BATTERY_CHARGE_PIN 39